Repository Weflo-B/Weflo-FE, pull requests merged in 2024-03, with the labels that each got.

#3 [FEAT] 전체 레이아웃 구현
  src/Home.tsx
  src/assets/icons/bag.svg
  src/assets/icons/check.svg
  src/assets/icons/drone.svg
  src/assets/icons/monitoring.svg
  src/assets/icons/more.svg
  src/assets/icons/paper.svg
  src/assets/icons/tracking.svg
  src/assets/logo/logo.webp
  src/constants/navigationMenuList.ts
  src/layouts/Header/Header.module.scss
  src/layouts/Header/index.tsx
  src/layouts/Layout.module.scss
  src/layouts/Layout.tsx
  src/layouts/Navigation/Navigation.module.scss
  src/layouts/Navigation/index.tsx
  src/pages/Tracking.tsx
  src/router.tsx
  src/styles/settings/reset.scss
  src/styles/style.scss
Labels: ✨Feature

#5 [Feat] 보험 가입 레이아웃 구현 - 가입자
  src/assets/icons/cancelBtn.svg
  src/assets/icons/process1.svg
  src/assets/icons/process2.svg
  src/assets/icons/process3.svg
  src/assets/icons/process4.svg
  src/assets/icons/rightChevron-process.svg
  src/assets/icons/rightChevron.svg
  src/components/Button.module.scss
  src/components/Button.tsx
  src/components/InsuranceContent.module.scss
  src/components/InsuranceContent.tsx
  src/components/InsuranceProcess.module.scss
  src/components/InsuranceProcess.tsx
  src/components/ProgressBar.module.scss
  src/components/ProgressBar.tsx
  src/pages/Insurance/Insurance.module.scss
  src/pages/Insurance/Insurance.tsx
  src/router.tsx
Labels: ✨Feature

#7 [FEAT] 주문/배송 조회 페이지 중 월별 주문/배송 조회 퍼블리싱 구현
  src/assets/icons/dropdown.svg
  src/assets/icons/rightChevron-process.svg
  src/components/Button.module.scss
  src/components/Button.tsx
  src/layouts/Header/Header.module.scss
  src/layouts/Layout.module.scss
  src/layouts/Layout.tsx
  src/layouts/Navigation/Navigation.module.scss
  src/pages/Insurance/Insurance.tsx
  src/pages/Tracking.tsx
  src/pages/Tracking/Tracking.module.scss
  src/pages/Tracking/atoms/MonthDropdown/MonthDropdown.module.scss
  src/pages/Tracking/atoms/MonthDropdown/index.tsx
  src/pages/Tracking/atoms/OrderInformation/OrderInformation.module.scss
  src/pages/Tracking/atoms/OrderInformation/index.tsx
  src/pages/Tracking/atoms/OrderList/OrderList.module.scss
  src/pages/Tracking/atoms/OrderList/index.tsx
  src/pages/Tracking/atoms/OrderSteps/OrderSteps.module.scss
  src/pages/Tracking/atoms/OrderSteps/index.tsx
  src/pages/Tracking/atoms/test.png
  src/pages/Tracking/index.tsx
  src/router.tsx
  src/styles/settings/color.scss
  src/types/index.ts
Labels: ✨Feature

#11 [FEAT] 주문/배송 상세 조회 퍼블리싱 구현
  package.json
  src/assets/icons/dialog/cancel.svg
  src/assets/icons/dialog/close.svg
  src/assets/icons/dialog/completed.svg
  src/assets/icons/order/arrived.svg
  src/assets/icons/order/delivery.svg
  src/assets/icons/order/received.svg
  src/assets/icons/order/route.svg
  src/components/Button.tsx
  src/components/Dialog/DefaultDialog.module.scss
  src/components/Dialog/DefaultDialog.tsx
  src/layouts/Navigation/Navigation.module.scss
  src/pages/Tracking/atoms/OrderList/index.tsx
  src/pages/TrackingDetail/TrackingDetail.module.scss
  src/pages/TrackingDetail/atoms/ProductInformation/ProductInformation.module.scss
  src/pages/TrackingDetail/atoms/ProductInformation/index.tsx
  src/pages/TrackingDetail/atoms/TrackingStep/TrackingStep.module.scss
  src/pages/TrackingDetail/atoms/TrackingStep/index.tsx
  src/pages/TrackingDetail/index.tsx
  src/router.tsx
  yarn.lock
Labels: ✨Feature

#18 [FEAT] 부품 주문 레이아웃 중 견적서 퍼블리싱 구현
  src/assets/icons/order-completed.svg
  src/layouts/Layout.module.scss
  src/pages/Estimate/Estimate.module.scss
  src/pages/Estimate/atoms/Completed.module.scss
  src/pages/Estimate/atoms/Completed.tsx
  src/pages/Estimate/index.tsx
  src/pages/Order/OrderEstimate.module.scss
  src/pages/Order/OrderEstimate.tsx
  src/pages/Tracking/Tracking.module.scss
  src/router.tsx
Labels: ✨Feature

#19 [CHORE] vercel 배포 관련 세팅
  src/pages/Insurance/GuestInsurance.tsx
  src/pages/Insurance/Insurance.tsx
  src/pages/Insurance/atoms/InsuranceContent/index.tsx
  src/pages/Insurance/atoms/InsuranceProcess/index.tsx
  src/pages/Insurance/atoms/ProgressBar/index.tsx
  src/pages/Order/OrderDetail.tsx
  src/pages/Order/atoms/DroneDetailItem.tsx
  src/pages/Order/atoms/DroneItem.tsx
  src/pages/Order/atoms/PartOnSale.tsx
  src/pages/Order/index.tsx
  vercel.json
Labels: ⚙ Chore

#23 [FEAT] 견적서 페이지 API 연동
  src/pages/Estimate/atoms/Completed.module.scss
  src/pages/Estimate/atoms/Completed.tsx
  src/pages/Estimate/index.tsx
  src/pages/Order/index.tsx
  src/services/estimateApi.ts
  src/types/index.ts
Labels: ✨Feature

#24 [FEAT] 주문/배송 페이지 API 연동
  src/components/Dialog/RadioButtonDialog.module.scss
  src/components/Dialog/RadioButtonDialog.tsx
  src/pages/Tracking/atoms/MonthDropdown/index.tsx
  src/pages/Tracking/atoms/OrderInformation/index.tsx
  src/pages/Tracking/atoms/OrderList/index.tsx
  src/pages/Tracking/atoms/OrderSteps/groupByOrderDate.ts
  src/pages/Tracking/atoms/OrderSteps/index.tsx
  src/pages/Tracking/index.tsx
  src/pages/TrackingDetail/TrackingDetail.module.scss
  src/pages/TrackingDetail/atoms/Information/BuyerInformation.tsx
  src/pages/TrackingDetail/atoms/Information/Information.module.scss
  src/pages/TrackingDetail/atoms/Information/SellerInformation.tsx
  src/pages/TrackingDetail/atoms/ProductInformation/ProductInformation.module.scss
  src/pages/TrackingDetail/atoms/ProductInformation/index.tsx
  src/pages/TrackingDetail/atoms/TrackingStep/index.tsx
  src/pages/TrackingDetail/index.tsx
  src/router.tsx
  src/services/trackingApi.ts
  src/types/index.ts
  tsconfig.json
Labels: ✨Feature

#27 [FIX] 1차 배포 후 오류 수정
  src/constants/navigationMenuList.ts
  src/layouts/Header/Header.module.scss
  src/layouts/Layout.module.scss
  src/layouts/Navigation/Navigation.module.scss
  src/layouts/Navigation/index.tsx
  src/pages/Insurance/GuestInsurance.tsx
  src/pages/Insurance/atoms/InsuranceDropDown/index.tsx
  src/pages/Order/index.tsx
  src/pages/Tracking/atoms/MonthDropdown/index.tsx
  src/pages/Tracking/index.tsx
  src/pages/TrackingDetail/TrackingDetail.module.scss
  src/pages/TrackingDetail/atoms/ProductInformation/index.tsx
  src/pages/TrackingDetail/atoms/TrackingStep/index.tsx
  src/pages/TrackingDetail/index.tsx
  src/router.tsx
  src/states/orderCount.ts
  src/styles/style.scss
  src/utils/orderCount.ts
Labels: 🐞 Bug

#28 [DEPLOY] 2차 배포
  src/constants/navigationMenuList.ts
  src/layouts/Header/Header.module.scss
  src/layouts/Layout.module.scss
  src/layouts/Navigation/Navigation.module.scss
  src/layouts/Navigation/index.tsx
  src/pages/Insurance/GuestInsurance.tsx
  src/pages/Order/index.tsx
  src/pages/Tracking/atoms/MonthDropdown/index.tsx
  src/pages/Tracking/index.tsx
  src/pages/TrackingDetail/TrackingDetail.module.scss
  src/pages/TrackingDetail/atoms/ProductInformation/index.tsx
  src/pages/TrackingDetail/atoms/TrackingStep/index.tsx
  src/pages/TrackingDetail/index.tsx
  src/router.tsx
  src/states/orderCount.ts
  src/styles/style.scss
  src/utils/orderCount.ts
Labels: 🚀 Deploy

#29 [DEPLOY] 3차 배포
  src/pages/Tracking/atoms/OrderInformation/index.tsx
  src/styles/style.scss
Labels: 🚀 Deploy
